# openapi: 3.0.3
# info:
#   title: My API 
#   version: 1.0.0
# servers: 
#   - url: https://cylsys-kodie-api-01-e3fa986bbe83.herokuapp.com/api/v1
# paths:
#   /auth/signup:
#     post:
#       summary: User Signup
#       requestBody:
#         required: true
#         content:
#           application/json:
#             example:
#               email: string
#               password: string
#               is_term_condition: boolean
#               is_privacy_policy: boolean
#       parameters:
#         - name: email
#           in: query
#           description: The email address of the user
#           required: true
#           schema:
#             type: string
#             example: "test@example.com"
#         - name: password
#           in: query
#           description: The password for the user
#           required: true
#           schema:
#             type: string
#             example: "securepassword"
#         - name: is_term_condition
#           in: query
#           description: Whether the user agrees to terms and conditions
#           required: true
#           schema:
#             type: boolean
#             example: true
#         - name: is_privacy_policy
#           in: query
#           description: Whether the user agrees to the privacy policy
#           required: true
#           schema:
#             type: boolean
#             example: true
#       responses:
#         '200':
#           description: User Signup Successful
#           content:
#             application/json:
#               example:
#                 message: User Signup Successful
#                 User_Key: string
#                 status: true
#         '409':
#           description: User Already Exists
#           content:
#             application/json:
#               example:
#                 message: User Already Exists
#                 status: false


openapi: 3.0.3
info:
  title: My API 
  version: 1.0.0
servers: 
  - url: https://cylsys-kodie-api-01-e3fa986bbe83.herokuapp.com/api/v1
paths:
  /signup:
    post:
      summary: User Signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "test@example.com"
                password:
                  type: string
                  example: "securepassword"
                is_term_condition:
                  type: boolean
                  example: true
                is_privacy_policy:
                  type: boolean
                  example: true
      responses:
        '200':
          description: User Signup Successful
          content:
            application/json:
              example:
                message: User Signup Successful
                User_Key: string
                status: true
        '409':
          description: User Already Exists
          content:
            application/json:
              example:
                message: User Already Exists
                status: false
