default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Cylsys@678
  host: 103.228.83.115

development:
  <<: *default
  database: Kodie_development

test:
  <<: *default
  database: Kodie_procedure_test


production:
  <<: *default
  database: Kodie_procedure_production
  username: Kodie_procedure
  password: <%= ENV["KODIE_PROCEDURE_DATABASE_PASSWORD"] %>
